rem Environment variables can be silently overwritten by these values!

set GRAILS_HOME=%SystemDrive%\dev\grails
set GROOVY_HOME=%SystemDrive%\dev\groovy
set JAVA_HOME=%SystemDrive%\dev\Java\jdk1.7.0_03

set EDITOR=%ProgramFiles%\Notepad++\notepad++.exe
set VISUAL=%EDITOR%

PATH F:\Python27;%PATH%

rem workaround because git doesn't pick up PATH correctly:
set GIT_SSH=%ProgramFiles%\PuTTY\plink.exe