#! /usr/bin/env python

import logging
import os, os.path

logger = logging.getLogger('' if '__main__' == __name__ else __name__)
debug, info, warning, error, fatal = logger.debug, logger.info, logger.warning, logger.error, logger.fatal

if '__main__' == __name__:
	logging.basicConfig(level=logging.DEBUG if __debug__ else logging.WARNING)
	import sys
