---
database_file: "/home/tb/GcsBox/timetrap/db"
round_in_seconds: 900
append_notes_delimiter: " "
formatter_search_paths:
- "/home/tb/.timetrap/formatters"
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- "/home/tb/.timetrap/auto_sheets"
default_command: 
auto_checkout: false
require_note: true
note_editor: false
